[{"schema_version":"1.3.1","id":"GO-2022-0380","modified":"2023-04-03T15:57:51Z","published":"2022-07-15T23:29:36Z","aliases":["CVE-2020-26892","GHSA-2c64-vj8g-vwrq","GHSA-4w5x-x539-ppf5"],"details":"The AccountClaims.IsRevoked and Export.IsRevoked functions improperly validate expired credentials using the current system time rather than the issue time of the JWT to be tested.\n\nThese functions cannot be used properly. Newer versions of the jwt package provide an IsClaimRevoked method which performs correct validation. In these versions, the IsRevoked method always return true.","affected":[{"package":{"name":"github.com/nats-io/jwt","ecosystem":"Go"},"ranges":[{"type":"SEMVER","events":[{"introduced":"0"},{"fixed":"1.1.0"}]}],"ecosystem_specific":{"imports":[{"path":"github.com/nats-io/jwt","symbols":["AccountClaims.IsRevoked","Export.IsRevoked"]}]}}],"references":[{"type":"ADVISORY","url":"https://advisories.nats.io/CVE/CVE-2020-26892.txt"},{"type":"FIX","url":"https://github.com/nats-io/jwt/commit/e11ce317263cef69619fc1ca743b195d02aa1d8a"}],"database_specific":{"url":"https://pkg.go.dev/vuln/GO-2022-0380"}},{"schema_version":"1.3.1","id":"GO-2022-0386","modified":"2023-04-03T15:57:51Z","published":"2022-07-01T20:11:22Z","aliases":["CVE-2021-3127","GHSA-62mh-w5cv-p88c","GHSA-9r5x-fjv3-q6h4","GHSA-j756-f273-xhp4"],"details":"Import tokens valid for one account may be used for any other account.\n\nValidation of Import token bindings incorrectly warns on mismatches, rather than rejecting the Goken. This permits a token for one account to be used for any other account.","affected":[{"package":{"name":"github.com/nats-io/jwt","ecosystem":"Go"},"ranges":[{"type":"SEMVER","events":[{"introduced":"0"},{"fixed":"1.2.3-0.20210314221642-a826c77dc9d2"}]}],"ecosystem_specific":{"imports":[{"path":"github.com/nats-io/jwt","symbols":["Account.Validate","AccountClaims.Validate","ActivationClaims.Validate","Import.Validate","Imports.Validate"]}]}},{"package":{"name":"github.com/nats-io/jwt/v2","ecosystem":"Go"},"ranges":[{"type":"SEMVER","events":[{"introduced":"0"},{"fixed":"2.0.1"}]}],"ecosystem_specific":{"imports":[{"path":"github.com/nats-io/jwt/v2","symbols":["Account.Validate","AccountClaims.Validate","Import.Validate","Imports.Validate"]}]}}],"references":[{"type":"ADVISORY","url":"https://advisories.nats.io/CVE/CVE-2021-3127.txt"},{"type":"FIX","url":"https://github.com/nats-io/jwt/pull/149"}],"database_specific":{"url":"https://pkg.go.dev/vuln/GO-2022-0386"}},{"schema_version":"1.3.1","id":"GO-2022-0402","modified":"2023-04-03T15:57:51Z","published":"2022-07-01T20:10:43Z","aliases":["CVE-2020-26521","GHSA-h2fg-54x9-5qhq","GHSA-hmm9-r2m2-qg9w"],"details":"A malicious account can create and sign a User JWT which causes a panic when decoded by the NATS JWT library.","affected":[{"package":{"name":"github.com/nats-io/jwt","ecosystem":"Go"},"ranges":[{"type":"SEMVER","events":[{"introduced":"0"},{"fixed":"1.1.0"}]}],"ecosystem_specific":{"imports":[{"path":"github.com/nats-io/jwt","symbols":["Account.Validate","AccountClaims.Validate","Export.Validate","Exports.Validate","Import.Validate","Imports.Validate"]}]}}],"references":[{"type":"FIX","url":"https://github.com/nats-io/jwt/pull/107"},{"type":"WEB","url":"https://advisories.nats.io/CVE/CVE-2020-26521.txt"}],"database_specific":{"url":"https://pkg.go.dev/vuln/GO-2022-0402"}}]