[{"schema_version":"1.3.1","id":"GO-2021-0109","modified":"2023-04-03T15:57:51Z","published":"2021-07-28T18:08:05Z","aliases":["CVE-2020-15223","GHSA-7mqr-2v3q-v2wm"],"details":"Due to improper error handling, an error with the underlying token storage may cause a user to believe a token has been successfully revoked when it is in fact still valid. An attackers ability to exploit this relies on an ability to trigger errors in the underlying storage.","affected":[{"package":{"name":"github.com/ory/fosite","ecosystem":"Go"},"ranges":[{"type":"SEMVER","events":[{"introduced":"0"},{"fixed":"0.34.0"}]}],"ecosystem_specific":{"imports":[{"path":"github.com/ory/fosite/handler/oauth2","symbols":["TokenRevocationHandler.RevokeToken"]}]}}],"references":[{"type":"FIX","url":"https://github.com/ory/fosite/commit/03dd55813f5521985f7dd64277b7ba0cf1441319"}],"database_specific":{"url":"https://pkg.go.dev/vuln/GO-2021-0109"}},{"schema_version":"1.3.1","id":"GO-2021-0110","modified":"2023-04-03T15:57:51Z","published":"2021-07-28T18:08:05Z","aliases":["CVE-2020-15222","GHSA-v3q9-2p3m-7g43"],"details":"Uniqueness of JWT IDs (jti) are not checked, allowing the JWT to be replayed.","affected":[{"package":{"name":"github.com/ory/fosite","ecosystem":"Go"},"ranges":[{"type":"SEMVER","events":[{"introduced":"0"},{"fixed":"0.31.0"}]}],"ecosystem_specific":{"imports":[{"path":"github.com/ory/fosite","symbols":["Fosite.AuthenticateClient","Fosite.NewAccessRequest","Fosite.NewRevocationRequest"]}]}}],"references":[{"type":"FIX","url":"https://github.com/ory/fosite/commit/0c9e0f6d654913ad57c507dd9a36631e1858a3e9"}],"database_specific":{"url":"https://pkg.go.dev/vuln/GO-2021-0110"}}]